language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"

matrix:
  allow_failures:
    - python: "3.3"
    - python: "pypy"

install:
  # install python requirements
  - pip install coveralls
  - pip install -e .[tests]

script:
  - make test

after_success:
  - coveralls
